commerce_payment.commerce_payment_gateway.plugin.lifepay:
  type: commerce_payment_gateway_configuration
  mapping:
    x_login:
      type: string
      label: 'Merchant ID'
    secret:
      type: string
      label: 'Secret'
    description:
      type: string
      label: 'Order description'
    vat_product:
      type: string
      label: 'Vat for product'
    vat_shipping:
      type: string
      label: 'Vat for shipping'
    use_ip_only_from_server_list:
      type: boolean
      label: 'Use server IP for callback only from list'
    server_list:
      type: string
      label: 'Acceptable server list'